# Generated by Django 3.2.3 on 2023-10-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='email',
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='alternate_email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='Дополнительный адрес электронной почты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicstatus',
            name='name',
            field=models.CharField(choices=[('passing', 'Проходит обучение'), ('academic_leave', 'Академический отпуск'), ('graduate', 'Выпускник'), ('expelled', 'Отчислен')], max_length=150, verbose_name='Учебный статус'),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='name',
            field=models.CharField(choices=[('job_search', 'Ищу работу'), ('employed', 'Трудоустроен'), ('internship_search', 'В поиске стажировки'), ('other', 'Другое')], max_length=100, verbose_name='Статус трудоустройства'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(choices=[('frontend_dev', 'Фронтенд-разработчик'), ('fullstack_dev', 'Фулстек-разработчик'), ('python_dev', 'Python-разработчик'), ('qa_engineer', 'Инженер по тестированию'), ('java_dev', 'Java-разработчик'), ('data_scientist', 'Специалист по data-science')], max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='grade',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('middle', 'Middle')], max_length=100, null=True, verbose_name='Грэйд'),
        ),
    ]
