# Generated by Django 3.2.3 on 2023-10-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentuser_academic_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='specialization',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='student_photos/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='student_resumes/', verbose_name='Резюме'),
        ),
    ]
